services:
  workspace:
    build: .
    container_name: BigData_workspace
    ports:
      - "8888:8888"   # Jupyter Lab
      - "6080:6080"   # Visualizador del Scraper (VNC)
      - "4040:4040"   # Spark UI
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=            # ← Configura tu token aquí
      - JUPYTER_PASSWORD=         # ← Configura tu password aquí
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_INSECURE_WRITES=true
      - DISPLAY=:99
    shm_size: "2gb"               # Evita fallos del navegador Selenium
    dns:
      - 8.8.8.8
    user: root
    restart: always
    depends_on:
      - mongodb
    networks:
      - bigdata_net

  # Contenedor de base de datos MongoDB (LOCAL)
  mongodb:
    image: mongo:latest
    container_name: bigdata_mongodb3
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db       # Persistencia local
    restart: always
    networks:
      - bigdata_net

  # Interfaz web para MongoDB LOCAL (puerto 8081)
  admin-db:
    image: mongo-express:latest
    container_name: BigData_Visualizer
    ports:
      - "8081:8081"
    environment:
      # Conexión al MongoDB LOCAL (no Atlas)
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123  # Cambia esto
      - VC_NODE_TLS_REJECT_UNAUTHORIZED=0
    dns:
      - 8.8.8.8
    restart: always
    depends_on:
      - mongodb
    networks:
      - bigdata_net

  # Gestor de archivos
  filebrowser:
    image: filebrowser/filebrowser
    container_name: BigData_FileBrowser
    ports:
      - "8082:80"
    volumes:
      - .:/srv
    environment:
      - FB_DATABASE=/database.db
    restart: always
    networks:
      - bigdata_net

networks:
  bigdata_net:
    driver: bridge
    name: BigData_Network_UCN

volumes:
  mongo_data: